#define _EXPAND(...) __VA_ARGS__
#define CONCAT_(l, r) l##r
#define CONCAT(l, r) CONCAT_(l, r)

#define _APPLY0(s, f, o)
#define _APPLY1(s, f, v, ...) f(v)
#define _APPLY2(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY1(s, f, __VA_ARGS__))
#define _APPLY3(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY2(s, f, __VA_ARGS__))
#define _APPLY4(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY3(s, f, __VA_ARGS__))
#define _APPLY5(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY4(s, f, __VA_ARGS__))
#define _APPLY6(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY5(s, f, __VA_ARGS__))
#define _APPLY7(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY6(s, f, __VA_ARGS__))
#define _APPLY8(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY7(s, f, __VA_ARGS__))
#define _APPLY9(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY8(s, f, __VA_ARGS__))
#define _APPLY10(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY9(s, f, __VA_ARGS__))
#define _APPLY11(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY10(s, f, __VA_ARGS__))
#define _APPLY12(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY11(s, f, __VA_ARGS__))
#define _APPLY13(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY12(s, f, __VA_ARGS__))
#define _APPLY14(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY13(s, f, __VA_ARGS__))
#define _APPLY15(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY14(s, f, __VA_ARGS__))
#define _APPLY16(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY15(s, f, __VA_ARGS__))
#define _APPLY17(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY16(s, f, __VA_ARGS__))
#define _APPLY18(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY17(s, f, __VA_ARGS__))
#define _APPLY19(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY18(s, f, __VA_ARGS__))
#define _APPLY20(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY19(s, f, __VA_ARGS__))
#define _APPLY21(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY20(s, f, __VA_ARGS__))
#define _APPLY22(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY21(s, f, __VA_ARGS__))
#define _APPLY23(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY22(s, f, __VA_ARGS__))
#define _APPLY24(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY23(s, f, __VA_ARGS__))
#define _APPLY25(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY24(s, f, __VA_ARGS__))
#define _APPLY26(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY25(s, f, __VA_ARGS__))
#define _APPLY27(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY26(s, f, __VA_ARGS__))
#define _APPLY28(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY27(s, f, __VA_ARGS__))
#define _APPLY29(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY28(s, f, __VA_ARGS__))
#define _APPLY30(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY29(s, f, __VA_ARGS__))
#define _APPLY31(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY30(s, f, __VA_ARGS__))
#define _APPLY32(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY31(s, f, __VA_ARGS__))
#define _APPLY33(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY32(s, f, __VA_ARGS__))
#define _APPLY34(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY33(s, f, __VA_ARGS__))
#define _APPLY35(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY34(s, f, __VA_ARGS__))
#define _APPLY36(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY35(s, f, __VA_ARGS__))
#define _APPLY37(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY36(s, f, __VA_ARGS__))
#define _APPLY38(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY37(s, f, __VA_ARGS__))
#define _APPLY39(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY38(s, f, __VA_ARGS__))
#define _APPLY40(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY39(s, f, __VA_ARGS__))
#define _APPLY41(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY40(s, f, __VA_ARGS__))
#define _APPLY42(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY41(s, f, __VA_ARGS__))
#define _APPLY43(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY42(s, f, __VA_ARGS__))
#define _APPLY44(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY43(s, f, __VA_ARGS__))
#define _APPLY45(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY44(s, f, __VA_ARGS__))
#define _APPLY46(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY45(s, f, __VA_ARGS__))
#define _APPLY47(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY46(s, f, __VA_ARGS__))
#define _APPLY48(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY47(s, f, __VA_ARGS__))
#define _APPLY49(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY48(s, f, __VA_ARGS__))
#define _APPLY50(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY49(s, f, __VA_ARGS__))
#define _APPLY51(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY50(s, f, __VA_ARGS__))
#define _APPLY52(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY51(s, f, __VA_ARGS__))
#define _APPLY53(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY52(s, f, __VA_ARGS__))
#define _APPLY54(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY53(s, f, __VA_ARGS__))
#define _APPLY55(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY54(s, f, __VA_ARGS__))
#define _APPLY56(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY55(s, f, __VA_ARGS__))
#define _APPLY57(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY56(s, f, __VA_ARGS__))
#define _APPLY58(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY57(s, f, __VA_ARGS__))
#define _APPLY59(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY58(s, f, __VA_ARGS__))
#define _APPLY60(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY59(s, f, __VA_ARGS__))
#define _APPLY61(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY60(s, f, __VA_ARGS__))
#define _APPLY62(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY61(s, f, __VA_ARGS__))
#define _APPLY63(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY62(s, f, __VA_ARGS__))
#define _APPLY64(s, f, v, ...) _APPLY1(s, f, v) s _EXPAND(_APPLY63(s, f, __VA_ARGS__))

#define _APPLY_X(x, s, f, v, ...) CONCAT(_APPLY, x)(s, f, v, __VA_ARGS__)